name: Pull Request verify

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Verify code formatting with dotnet
        run: dotnet format -v detailed --verify-no-changes

      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build

      - name: Publish .NET Core application
        run: dotnet publish -c Release -o ./artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./artifacts
