name: Pull Request verify & test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR verify & test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Verify code formatting with dotnet
        run: dotnet format -v detailed --verify-no-changes

      - name: Build .NET Core application
        run: dotnet build -c Release

      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build
