name: secrets

on:
  workflow_dispatch:

jobs:
  build:
    name: secrets
    runs-on: ubuntu-latest

    steps:
      - name: Verify code formatting with dotnet
        run: dotnet format -v detailed --verify-no-changes
