name: secrets

on:
  pull_request:
    branches: [ "main" ]

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api.csproj"

jobs:
  build:
    name: secrets
    runs-on: ubuntu-latest

    steps:
      - name: Print env var
        run: echo "$API_CSPROJ_PATH"
